### ISSUE TITLE
LogicException You must call one of in() or append() methods before iterating over a Finder.

### ISSUE THREAD

**Issue by misog** [Wulfheart/laravel-actions-ide-helper#13]
Hi, after running `php artisan ide-helper:actions` this error occurs:

```
   LogicException 

  You must call one of in() or append() methods before iterating over a Finder.

  at vendor/symfony/finder/Finder.php:611
    607▕      */
    608▕     public function getIterator(): \Iterator
    609▕     {
    610▕         if (0 === \count($this->dirs) && 0 === \count($this->iterators)) {
  ➜ 611▕             throw new \LogicException('You must call one of in() or append() methods before iterating over a Finder.');
    612▕         }
    613▕ 
    614▕         if (1 === \count($this->dirs) && 0 === \count($this->iterators)) {
    615▕             $iterator = $this->searchInDirectory($this->dirs[0]);

      +8 vendor frames 
  9   [internal]:0
      Illuminate\Support\LazyCollection::Illuminate\Support\{closure}()

      +2 vendor frames 
  12  [internal]:0
      Wulfheart\LaravelActionsIdeHelper\Service\ActionInfoFactory::Wulfheart\LaravelActionsIdeHelper\Service\{closure}()
```
Laravel 9.16.0
PHP 8.1.3

**Comment by Wulfheart** [comment]
Do you have a demo repo where this issue happens?

**Comment by misog** [comment]
No, but it happens also on a fresh project without `app/Actions` directory. When I create `app/Actions` directory then it works:
```
IDE Helpers generated for Laravel Actions at ...
```

I think it should not throw the error if no Actions directory is found.

Also Laravel Actions 2 can be placed everywhere so there should be a way how to configure paths or the IDE helper just could rescan all folders recursively.

**Comment by Wulfheart** [comment]
This project is in [YOLO-mode](https://github.com/Wulfheart/laravel-actions-ide-helper?tab=readme-ov-file#yolo-ware) now. Please feel free to re-open if you think it still applies.
