### ISSUE TITLE
Remove unused deps

### ISSUE THREAD

**Issue by Ridzhi** [Wulfheart/laravel-actions-ide-helper#14]
Hi, please remove "ridzhi/docbuilder": "^1.0" from your composer.json. You don't use it,  and i am going to delete this repository :)

**Comment by Wulfheart** [comment]
Thanks for the heads up.

**Comment by hcbaxiom** [comment]
any updates on this? "ridzhi/docbuilder": "^1.0" is no more available, causing failed builds, we'll have to abandon you otherwise

**Comment by clarkeash** [comment]
Yeah just hit this issue too, I have removed this package for now.

**Comment by Wulfheart** [comment]
Thanks for the notification. Please update it to 0.5.0 then it should(!) work again. If this unfortunately does not work for you feel free to open a PR.

**Comment by vpratfr** [comment]
Seems like it worked. 

`composer update` solved the same issue here.

Thanks.

**Comment by reinhardt021** [comment]
tried updating to 0.5.0 but then got this issue when running `composer install` - am I missing something here? do I need to update laravel versions? 😕 
![Screenshot 2023-06-28 at 10 38 36](https://github.com/Wulfheart/laravel-actions-ide-helper/assets/1851287/7116172e-0d89-4d25-b79f-245083ce872c)

**Comment by Wulfheart** [comment]
@reinhardt021 Yes. 
https://github.com/Wulfheart/laravel-actions-ide-helper/issues/18
