### ISSUE TITLE
PHP 8.2 Support?

### ISSUE THREAD

**Issue by goper-leo** [Wulfheart/laravel-actions-ide-helper#19]
Do you have plans to support `php 8.2`? 

Thanks for this package.

**Comment by Wulfheart** [comment]
Phew. I could merge a PR. Otherwise I am a little bit short on time right now.

**Comment by goper-leo** [comment]
@Wulfheart [PR](https://github.com/Wulfheart/laravel-actions-ide-helper/pull/20).

Thanks.

**Comment by Wulfheart** [comment]
Thanks. v0.6.0
