### ISSUE TITLE
Version 0.7.0 and Laravel 11

### ISSUE THREAD

**Issue by Nezimed** [Wulfheart/laravel-actions-ide-helper#22]
Trying to use the new version on a laravel 11 project:

```
Problem 1
    - lorisleiva/lody v0.4.0 requires illuminate/contracts ^8.0|^9.0|^10.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.3] but these were not loaded, likely because it conflicts with another require.
    - wulfheart/laravel-actions-ide-helper v0.7.0 requires lorisleiva/lody ^0.4.0 -> satisfiable by lorisleiva/lody[v0.4.0].
    - Root composer.json requires wulfheart/laravel-actions-ide-helper ^0.7.0 -> satisfiable by wulfheart/laravel-actions-ide-helper[v0.7.0].
```
Maybe because laravel-actions 2.8 uses lody version 0.5.0

**Comment by Wulfheart** [comment]
Could you please fix this and open a PR for it?

**Comment by Nezimed** [comment]
I opened a PR, it was my first so let me know if something is missing

**Comment by Wulfheart** [comment]
This project is in [YOLO-mode](https://github.com/Wulfheart/laravel-actions-ide-helper?tab=readme-ov-file#yolo-ware) now. Please feel free to re-open if you think it still applies.

You should be good to go btw.
