### ISSUE TITLE
Php 8.1 intersection types don't work

### ISSUE THREAD

**Issue by brecht-vermeersch** [Wulfheart/laravel-actions-ide-helper#4]
This

    public function handle(Permissionable&Model $permissionable): Permission

Produces

 * @method static void run()    <-- empty
 */
class CreatePermission
{
}

**Comment by Wulfheart** [comment]
This might be true. Haven’t had the time to take a look at it. Would you be willing to work on it with some guidance?

**Comment by brecht-vermeersch** [comment]
Hi Wulfheart

I've looked through the project files and already found some areas I could improve on (if you give me permission to do so).

* improve trait discovery
   * the author of laravel actions recently made a package Lody that makes this very easy
   * give the users a config file where they can input an array of paths to search (instead of always using the app folder)
* Adding the union and intersection types
* Adding optional parameters
* Add tests for everything (will probably need to refactor some things to make testing easier)
* Allow the option to write the docblocks to the actions file instead of seperate file (like barry ide helper)

If you give me the go ahead on any of these features, I will start looking into them.

**Comment by Wulfheart** [comment]
Hey @lurza,
that would be great. I would really appreciate it if you could start by adding tests first and the rest after that. 
I currently have limited time due to the nearing end of my bachelor's degree but I will take the time and review it. Furthermore I will add an GitHub Action for the tests to run automatically on Push and PR.

**Comment by Wulfheart** [comment]
@lurza I just published a new version but I think it is failing right now. Feel free to take a look at it. I would really appreciate it!

**Comment by Wulfheart** [comment]
This project is in [YOLO-mode](https://github.com/Wulfheart/laravel-actions-ide-helper?tab=readme-ov-file#yolo-ware) now. Please feel free to re-open if you think it still applies.
