### ISSUE TITLE
[Feature] Folder config

### ISSUE THREAD

**Issue by robsontenorio** [Wulfheart/laravel-actions-ide-helper#6]
Hi!

It would be nice if we can configure custom folders for actions.

Currently my actions are placed on `/app-modules/**/Actions`, not `/app/**/actions`.

For reference, laravel-ide-helper package allow us to configure models folder with glob expressions, for instance.

**Comment by dynamiccommerce** [comment]
I am currently very limited on time. 
However, if you would be willing to contribute it and write Pest tests for it I would merge it. 👍🏻

**Comment by Wulfheart** [comment]
I am currently very limited on time. 
However, if you would be willing to contribute it and write Pest tests for it I would merge it. 👍🏻

**Comment by Wulfheart** [comment]
Still open, but with v0.2.0 I think it got a lot easier to add it.

**Comment by Wulfheart** [comment]
This project is in [YOLO-mode](https://github.com/Wulfheart/laravel-actions-ide-helper?tab=readme-ov-file#yolo-ware) now. Please feel free to re-open if you think it still applies.
