### ISSUE TITLE
Class "Composer\Autoload\ClassMapGenerator" not found

### ISSUE THREAD

**Issue by renepardon** [Wulfheart/laravel-actions-ide-helper#7]
I have the same problem and found this issue before: https://github.com/barryvdh/laravel-ide-helper/issues/709

```bash
Class "Composer\Autoload\ClassMapGenerator" not found

  at vendor/wulfheart/laravel-actions-ide-helper/src/Commands/LaravelActionsIdeHelperCommand.php:38
     34▕             ->files()
     35▕             ->in(app_path())
     36▕             ->name('*.php');
     37▕ 
  ➜  38▕         $map = collect(ClassMapGenerator::createMap($finder->getIterator()));
     39▕         // dd($map);
     40▕         $classes = $map->keys();
```

```bash
PHP 8.1.1 (cli) (built: Dec 31 2021 07:26:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
```

```json
"lorisleiva/laravel-actions": "^2.2",
"wulfheart/laravel-actions-ide-helper": "^0.1.0"
```

I tried already a composer update but without any changes.

**Comment by Wulfheart** [comment]
Did you try deleting the vendor folder?

**Comment by renepardon** [comment]
> Did you try deleting the vendor folder?

Hi @Wulfheart 
yes, without success.

**Comment by Wulfheart** [comment]
Hm. I currently don't have the mental space to tackle this issue due to the exam period. Either you take a look at it and open a PR or you wait until mid of February when I have the time to take a look at it. ☺️

**Comment by abobus-2288** [comment]
There's still an issue in 2023.
Just installed the library, but i can't use it because of this problem
I use version 1.0, and i this is the code that was installed by composer: use Composer\Autoload\ClassMapGenerator;

**Comment by Wulfheart** [comment]
Could you please try to debug it and PR it?

**Comment by abobus-2288** [comment]
I just made all changes from [this](https://github.com/Wulfheart/laravel-actions-ide-helper/pull/9) PR. Idk why composer installed the library without these changes. I used version 1 beta

**Comment by Wulfheart** [comment]
Wait. @abobus-2288 which version do you use? Please send the composer.json and the composer.lock.

**Comment by Wulfheart** [comment]
This project is in [YOLO-mode](https://github.com/Wulfheart/laravel-actions-ide-helper?tab=readme-ov-file#yolo-ware) now. Please feel free to re-open if you think it still applies.
